### ISSUE TITLE
Non-functional requirements and investigation

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/interactsh#112]
TODO:
- [x] load testing & profiling
- [x] come up with a scaling solution

Reference: https://github.com/projectdiscovery/interactsh/issues/107

**Comment by ehsandeep** [comment]
As a result of this investigation, we have identified a few issues that are fixed in [refactor-server](https://github.com/projectdiscovery/interactsh/tree/refactor-server) and soon will be merged into after completing ongoing testing.

For scaling, we are going to use a pool of interactsh servers to distribute the load.

**Comment by Ice3man543** [comment]
The investigation reported that the ccache was getting blocked under heavy load hence the requests were getting timed out.  The db was changed to use github.com/goburrow/cache and instrumentation was added during testing as well which confirmed that the latency and the cache response times both improved very much using the new cache and the requests didn't get stuck under heavy load. Hence, we can go ahead and merge the refactor after a few changes.

**Comment by ehsandeep** [comment]
Follow up ticket for scaling solution - https://github.com/projectdiscovery/interactsh/issues/170
