### ISSUE TITLE
No DNS request received with systemd-resolved

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/interactsh#141]
Hello,
I've observed that when `systemd-resolved` is used, DNS requests are not received on the Interactsh server.

![image](https://user-images.githubusercontent.com/17493961/147235465-0a93e6a7-529c-4af4-b6ac-2e2c3a47aeae.png)

We've also tested with a friend on two different private Interactsh installations, without really understanding the source problem, we think that it comes directly from `interactsh-server` because it's a problem that I don't encounter with my private burp collaborator or my custom dns server.

To reproduce it is enough to use a server ubuntu 20.04 / Debian 11 with systemd-resolved (I did not test other OS)

Regards

**Comment by Serizao** [comment]
I have observed the same problem with some servers. At first I thought it was the TTL but even when recompiling with a lower TTL I still have the problem. I could observe that it came from interactsh because on the same server it works with a program I made (burp collborator like) and not with interact sh.
