### ISSUE TITLE
Nuclei spams AAAA requests to the Interact server

### ISSUE THREAD

**Issue by 0x0luke** [projectdiscovery/interactsh#33]
Hi, I'm using Nuclei, interact and notify to spot OOB requests, however the webhook is spamming me with this

![image](https://user-images.githubusercontent.com/24577556/118192218-b786c680-b43d-11eb-9f8d-c8fdfcd886c3.png)

Could a IP filter argument be added so they're not passed through into STDOUT?

**Comment by ehsandeep** [comment]
@0x0luke do you mind sharing how you using interactsh url in your template, that might be a potential issue here.

**Comment by 0x0luke** [comment]
It's just taking the output from nuclei via a pipe and passing it onto notify, such as:

![image](https://user-images.githubusercontent.com/24577556/118206277-10645800-b45a-11eb-9955-2f6d1d50505b.png)


Nothing special about the setup i'm doing. Only thing I can think of is the headless chrome?

**Comment by geeknik** [comment]
I believe all of the spammy look-ups are because you defined a subdomain as your `-interactsh-url` instead of setting it to just `http://interact.sh`. Nuclei will handle the generation of the payload  for the 6 templates in the community repo that call {{interactsh-url}} and nuclei will also notify you of any OOB interactions during your scan. You can further configure the interactions with these options: `-interactions-cache-size`, `-interactions-cooldown-period`, `-interactions-eviction`, and `-interactions-poll-duration`.

**Comment by geeknik** [comment]
Come to think of it, I don't even think you need `-interactsh-url` unless you're running your own private server. There is more information on that [here](https://blog.projectdiscovery.io/nuclei-interactsh-integration/).

**Comment by ehsandeep** [comment]
Yeah, that's what we were suspecting, that's not how that flag supposed to use `-interactsh-url` is flag to support self-hosted OOB instance for nuclei, otherwise as default, it will make use of hosted version `https://www.interact.sh`, and you don't need to feed any value.

Interactsh is integrated within nuclei and will auto-generate and correlated things for you, you don't need to self-generated payloads, more details listed here https://blog.projectdiscovery.io/nuclei-interactsh-integration/

@0x0luke FYI^

**Comment by 0x0luke** [comment]
Ah interesting, thanks guys, I wasn't sure how it worked
