### ISSUE TITLE
https://app.interactsh.com/#/ has some SSL/ caching issues not sure but the server gets unavailable at times

### ISSUE THREAD

**Issue by tess-ss** [projectdiscovery/interactsh#380]
Hi team,

The https://app.interactsh.com/#/ server works when I visit the URL but after some time like 5-10 minutes the server gets Unavailable and sometimes I also get SSL cache issue. Please see the screenshots attached below for clear demonstration, I tried clearing my browser cache, session data, cookies and everything but still the issue exists in my region I guess?

### Server Unavailable 
![image](https://user-images.githubusercontent.com/65326024/191788033-fece8b98-c77c-4642-967e-0de364e5cbd9.png)

<img width="1912" alt="Screen Shot 2022-09-22 at 11 18 12 AM" src="https://user-images.githubusercontent.com/65326024/191787670-f7c2b3a7-1cb1-4bb4-a35a-9abd387403dc.png">

**Comment by wis4nggeni** [comment]
![image](https://user-images.githubusercontent.com/61108897/192459327-435af543-27b3-44de-8e41-3332f3cb78f9.png)
![image](https://user-images.githubusercontent.com/61108897/192459839-b9c75e6d-4e41-4b8b-b21b-33a63a5cfba6.png)

I got the same Issue since a couple weeks ago. I can't seem to fetch the interact.sh poll url, it returns connection timeout error.

I think this only happen on **_interact.sh_** url, since now you're using **_oast.fun_** or **_oastify.com_** url and running a new instance seems fine.

The thing is, I can't change to a new callback urls, since I've already planted the url to many bug bounty targets using my method and it's permanent, I can't change it anymore.

Your help would be very appreciated.

**Comment by ehsandeep** [comment]
@wis4nggeni since `interact.sh` is having an issue due to load, you need to click on reset to use other default servers, we try to keep public servers as available as possible but it's always subject to down/restart depending on the load, so I can only suggest to reset to switch with other servers.

unfortunately, you need to redo your automation or use a self-hosted server.

**Comment by wis4nggeni** [comment]
I actually don't mind using a self-hosted server but unfortunately the callback URL is already planted on my targets with an interact.sh url and can't be changed whatsoever.

Can we somehow do something about it? maybe forward the callbacks to my self-hosted server? I'd be extremely grateful if it's possible.

Is there any private contact that I can reach to communicate this matter?

**Comment by ehsandeep** [comment]
It was an issue with interactsh server in use - `interact.sh`, which is not used anymore; default server used in [interactsh-web](https://github.com/projectdiscovery/interactsh-web) client is also has been updated.
