### ISSUE TITLE
Implement XSSHunter

### ISSUE THREAD

**Issue by PatrikFehrenbach** [projectdiscovery/interactsh#394]
Interact would be a perfect place to inherit the functionality of XSShunter (https://github.com/mandatoryprogrammer/xsshunter-express). 

Pretty please ❤️

**Comment by ehsandeep** [comment]
@PatrikFehrenbach Thanks for creating this issue. We will work on it, either in interactsh or in a different project.

**Comment by juanmera** [comment]
I wanted to propose the same. Now that xsshunter.com is been deprecated, it would be great run just one self-hosted service for all the probing and have the information from the XSS probe reported to them same interachsh client/burp extension. Also, each correlation id could be configured to add its own scripts, beyond html2canvas and basic recon.

**Comment by Mzack9999** [comment]
Todo:
- [ ] Implement backend logic
Requires discussion around:
- [ ] UI implementation
- [ ] Authenticathed vs Anonymous Encrypted access

**Comment by Mzack9999** [comment]
https://github.com/projectdiscovery/interactsh-web has outdated web packages and is out of sync with the current deployment (e.g. LDAP).
It could make sense to embed the http server within the interactsh-client CLI so that it can be run locally and provide the same UI experience as the xss-hunter web interface.

**Comment by ehsandeep** [comment]
@PatrikFehrenbach Unfortunately, due to limited bandwidth, we decided not to implement this support in interactsh project; we are still looking to make interactsh project more stable with its core features.

As a suggestion for an alternative of the XSS Hunter project, https://github.com/ssl/ezXSS looks good and is actively maintained.
